### ISSUE TITLE
Open items to discuss

### ISSUE THREAD

**Issue by alistair-clark** [UBC-MDS/dsci_532_group-209#8]
Hi guys,

I'm opening an issue to share some notes (and to practice using Github issues):

- Any ideas on how we source the data to the original owners?
- There are lots of features of the `map_plot()` function that can be updated (plot width and height, tooltip language, legend size and location, etc.). Please make updates if you see opportunities.
- Some ideas for other features if we feel like doing extra after we get the dashboard looking good: a 2nd dropdown for zooming in on continents, a bar chart showing the top 10 countries (I've already created this function), interactivity like clicking on a country to get more info.

**Comment by schepal** [comment]
In regards to the first two points:

- I added the data source to FiveThirtyEight

- The edits we made to `map_plot()` on the updated dashboard look good and fit well in fullscreen.
